from paretos.exceptions import ParetosError


class AuthenticationError(ParetosError):
    pass
